# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# CNAME: hubs.kristallum.com
# Setup
title:            Hyde
tagline:          'A Jekyll theme'
description:      'TBD'
url:              http://ipv6.github.io/kristallum/
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/IPv6/kristallum/
